
USE novusdb;


-- CREATE STATEMENTS
Create Table STUDENTS (   

	 ID 			int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,                   
	 SFIRSTNAME     varchar(15),                               
	 SLASTNAME      varchar(15),                               
	 GENDER         varchar(15),                               
	 ADDRESS        varchar(35), 
	 CITY           varchar(25),                            
	 DEPARTMENT     varchar(5),                               
	 SCHOOL         varchar(35),                             
	 PFIRSTNAME     varchar(15),                              
	 PLASTNAME      varchar(15),                              
	 PHONE_NUMBER   varchar(14),                              
	 DATE_ENROLLED  varchar(13),                               
	 ATTENDANCE     varchar(10),
	 createdDateTime datetime,
	 modifiedDateTime datetime

);

 -- CREATE INSERT STATEMENT
INSERT INTO STUDENTS (SFIRSTNAME, SLASTNAME, GENDER, ADDRESS, CITY, DEPARTMENT, SCHOOL, PFIRSTNAME, PLASTNAME, PHONE_NUMBER, DATE_ENROLLED, ATTENDANCE, createdDateTime, modifiedDateTime)
VALUES ('Robert', 'Torvalds', 'Male', '4410 Porter Street', 'MI, Detroit', 'Beni','Northwestern High School', 'Linda', 'Torvalds', '(704) 243-8845', '03/13/2025', 'Frequent', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);


Create Table STUDENTS_DELETED (
   
	 ID 			int PRIMARY KEY,                   
	 SFIRSTNAME     varchar(15),                               
	 SLASTNAME      varchar(15),                               
	 GENDER         varchar(15),                               
	 ADDRESS        varchar(35),                              
	 CITY           varchar(25),                              
	 DEPARTMENT     varchar(5),                               
	 SCHOOL         varchar(35),                              
	 PFIRSTNAME     varchar(15),                              
	 PLASTNAME      varchar(15),                              
	 PHONE_NUMBER   varchar(14),                              
	 DATE_ENROLLED  varchar(13),                               
	 ATTENDANCE     varchar(10),
	 createdDateTime datetime,
	 modifiedDateTime datetime
	 
);

Create Table USERS (

	ID 				int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,    
	ACCOUNT			varchar(25) NOT NULL,      
	PASSWORD		varchar(256) NOT NULL

);

INSERT INTO USERS (ACCOUNT, PASSWORD)
VALUES ('Administrator', 'admin');

INSERT INTO USERS (ACCOUNT, PASSWORD)
VALUES ('Mentor', '1234');
