using System;
using System.Collections.Generic;

//You are given two strings s and t.
//String t is generated by random shuffling string s and then add one more letter at a random position.
//Return the letter that was added to t.
namespace Find_the_Difference
{
    class Program
    {
        static void Main(string[] args)
        {
            char c = ' ';
            string s = "abcd", t = "abcde";
            char[] ch = String.Concat(s,t).ToCharArray();
            Dictionary<char,int> dict = new Dictionary<char,int>();
            
            for(int i = 0;i <= ch.Length-1;i++) {
                if(!dict.ContainsKey(ch[i]))
                    dict.Add(ch[i],0);

                dict[ch[i]]++;
    
            }

            foreach(KeyValuePair<char,int> kv in dict) {
                if(kv.Value % 2 != 0)
                    c = kv.Key;
                
            }
            Console.WriteLine(c);
            
        }
    }
}
